Added more doc strings
scalableminds/webknossos-libs pull request #1225
Opened 2024-12-02 16:46 UTC by hotzenklotz

### Description:
- I updated even more classes to use Google-Style doc strings and enhance the documentation that way

### Issues:
- fixes #...

### Todos:
Make sure to delete unnecessary points or to check all before merging:
 - [ ] Updated Changelog
 - [x] Updated Documentation
 - [ ] Added / Updated Tests
 - [ ] Considered adding this to the Examples

2024-12-03 09:34 UTC, hotzenklotz commented on webknossos/webknossos/dataset/mag_view.py
> +            with ProcessPoolExecutor() as executor:
This is likely incorrect. Don't know the correct usage for executors, though.

2024-12-03 09:34 UTC, hotzenklotz commented on webknossos/webknossos/dataset/mag_view.py
> +            with ProcessPoolExecutor() as executor:
This is likely incorrect. Don't know the correct usage, though.

2024-12-03 09:34 UTC, hotzenklotz commented on webknossos/webknossos/dataset/mag_view.py
> +            with ProcessPoolExecutor() as executor:
This is likely incorrect. Don't know the correct usage, though.

2024-12-03 16:43 UTC, markbader requested changes
Looks mostly good already. 
Nevertheless, I found some issues like missing arguments, wrongly used methods and as you already commented some issues with the usage of executors. As there are quite a lot of newly added comments, I hope that I found most of the mistakes in the generated doc strings.

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/dataset/view.py
> +            bbox = NDBoundingBox((10, 10, 0), (50, 50, 10))
NDBoundingBox constructor needs additional arguments e.g.:`axis=("x", "y", "z")` and `index=(1, 2, 3)`.

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/dataset/view.py
> +            bbox = NDBoundingBox((10, 10, 0), (50, 50, 10))
Same as above, either use BoundingBox or add `axis` and `index` arguments.

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/dataset/view.py
> +                in Mag(1). Defaults to None.
This argument list is incomplete. Missing: offset (deprecated), dimension, json_update_allowed, use_logging

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/dataset/view.py
> +                writer.write(slice_data)
The BufferedSliceWriter receives data when the `send` method is called.

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/dataset/view.py
> +                Defaults to False.
This args list does not include offset and size

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/dataset/view.py
> +            )
The BufferedSliceReader is a context manager. The usage shown in the examples is wrong. It should be used like:

```python
    view = ...
    with view.get_buffered_slice_reader() as reader:
        for slice_data in reader:
            ...
```

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/dataset/view.py
> +            from concurrent.futures import ThreadPoolExecutor
Why is a ThreadPoolExecutor imported here?

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/dataset/view.py
> +            with ProcessPoolExecutor(max_workers=4) as executor:
As above, we usually use `get_executor_for_args(None)`.

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/dataset/view.py
> +            with ThreadPoolExecutor(max_workers=4) as executor:
Same as above, `with get_executor_for_args() as executor`

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/dataset/view.py
> +            chunk_shape (Optional[Vec3IntLike], optional): Size of chunks to use for
chunk_shape is no argument of this method.

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/dataset/view.py
> +                If None, no progress bar is shown. Defaults to None.
The deprecated `args` argument is missing in this list.

2024-12-03 16:43 UTC, markbader commented on webknossos/webknossos/annotation/annotation.py
> +                Deprecated and no longer required.
Most other deprecated arguments start with: `⚠️ Deprecated.`

2024-12-04 13:34 UTC, hotzenklotz commented
Thanks for the review. I applied most of your feedback and removed the parallel executor example for now. Perhaps that's too much detail for each method and should be covered somewhere else in more detail (in the future).

2024-12-04 15:23 UTC, markbader approved these changes
Looks much better. I found only a few issues and created suggestions for them.

2024-12-04 15:23 UTC, markbader commented on webknossos/webknossos/dataset/mag_view.py
> +            - Other view must have chunks_per_shard = 1
Chunks per shard = 1 does not sound right, as the value must be specified for x, y and z. What is asserted in the function is that `chunks_per_shard` is 1 in all dimensions, i.e. that exactly one chunk is stored in a file. This property is called `file_len=1` in the assertion.
```suggestion
            - Other view must have file_len = 1
```

2024-12-05 09:16 UTC, hotzenklotz commented on webknossos/webknossos/dataset/view.py
> +        _mag (Mag): Magnification level of the view.
Good catch. I updated the docstrings for the properties accordingly.

2024-12-05 10:41 UTC, merged